#!/bin/bash

# Criando variaveis para o script.

user=otrs # usuário que é usado para o Daemon do otrs
cmd=`grep $user /etc/passwd | awk -F: {'print $1'}` # comando pra saber se o usuário existe
linkDownload=$LINK
znunyVersion=$VERSION

# Começando o codigo.

if [ "$cmd" = "$user" ]; then
    echo "Usuário ja existe!"
    echo "Pulando para parte dos comando em segundo plano..."

else
    # Add user for Debian/Ubuntu
    echo "Criando usuário..."
    useradd -d /opt/otrs -c 'Znuny user' -g www-data -s /bin/bash -M -N otrs
    echo "Usuário criado!"

    # Download Znuny
    cd /opt
    wget $linkDownload

    # Extract
    tar *.tar.gz

    # Renomeando pasta
    mkdir /opt/otrs
    mv /opt/znuny-$znunyVersion/* /opt/otrs/

    # Criando um arquivo de config
    cp /opt/otrs/Kernel/Config.pm.dist /opt/otrs/Kernel/Config.pm

    # Adicionando permissões
    /opt/otrs/bin/otrs.SetPermissions.pl

    
    su -c 'cd /opt/otrs/var/cron; for foo in *.dist; do cp $foo `basename $foo .dist`; done' -s /bin/sh $user

    # Criando copia do config do apache
    ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/conf-available/zzz_znuny.conf

    # Enable the needed Apache modules:
    a2enmod perl headers deflate filter cgi
    a2dismod mpm_event
    a2enmod mpm_prefork
    a2enconf zzz_znuny

    # Enable Znuny Cron - Switch to the otrs user:
    su -c '/opt/otrs/bin/Cron.sh start' -s /bin/sh $user
    
    # Enable Znuny Daemon
    su -c '/opt/otrs/bin/otrs.Daemon.pl start' -s /bin/sh $user

    echo "Feito o download e configuração inicial do Znuny."
fi


# Enable Znuny Cron - Switch to the otrs user:
su -c '/opt/otrs/bin/Cron.sh start' -s /bin/sh $user

# Enable Znuny Daemon
su -c '/opt/otrs/bin/otrs.Daemon.pl start' -s /bin/sh $user

# Subindo serviço do apache.
/usr/sbin/apache2ctl -D FOREGROUND